### ISSUE TITLE
A bug

### ISSUE THREAD

**Issue by Ahmed490971** [notpoiu/mspaint#1]
When you use delete seek DURING the eyes thing, you can't open doors and you get tp'ed back, v3 gonna have auto loot? I'm on mobile so I don't see auto loot

**Comment by notpoiu** [comment]
> v3 gonna have auto loot?

v2 has autoloot which is auto interact and we are not making a major release soon, we will be however making this script more stable and usable on more executors.

> I'm on mobile so I don't see auto loot

In a future update we will make sure to implement a way for mobile users to use auto interact. Our main focus was releasing the script as it was made in about two days.

> you use delete seek DURING the eyes thing, you can't open doors and you get tp'ed back

Delete seek usually requires some time before it has full effect, depending on your executor, mspaint can fallback to anchoring your character and waiting for seek's collision to be destroyed.

As for the teleporting issue that stems from using speed bypass, for the most stable performance i would recommend using no speed bypass and a speed boost of 6.

I would also generally recommend NOT using delete seek FE in floor two as that messes with your game however in later updates we will be adding features to make it more stable during floor two seek chases.

**Comment by Ahmed490971** [comment]
is deleting figure possible? I wanna see that

**Comment by notpoiu** [comment]
> is deleting figure possible? I wanna see that, it'll help my noob friends, and if it's possible, will it work for door 100?

While i have not tested delete figure in the current update I will test it soon. But it should normally be possible.

> By the way, May I get permission to showcase this script?

you have full permission to showcase the script, if you want our youtube chanels to tag us here it is:
https://www.youtube.com/@deividcomsono https://www.youtube.com/@_upio
