### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by loxchmorez** [notpoiu/mspaint#11]
Add checks for auto interaction, for example, if the item is a bandage, then the cheat will pick up the item only if the player has less than 100 HP. We also check to see if the player has a flashlight when picking up batteries. I would also like to see anti A-90 and Auto Closet. It would be cool to also add automatic passage of Rooms/doors/mines.

**Comment by notpoiu** [comment]
anti A-90 has been implemented, I will soon add it if you have the modifier that adds a-90 to the hotel. as for the auto interact checks, that will take more processing which in turn makes the script laggier. Auto Closet is complicated as accounting for every single entity is not easy to do, as such its probably not coming to mspaint
