### ISSUE TITLE
Water oxygen bug

### ISSUE THREAD

**Issue by Hoangnguyen72628** [notpoiu/mspaint#15]
Hey again, every button where I enabled and then when I get close to the water, it actually just appeared the wet icon at the bottom left, but when I get into he water, the oxygen appears and decreasing after the oxygen notify enabled.

**Comment by deividcomsono** [comment]
what do you mean?

**Comment by Hoangnguyen72628** [comment]
> what do you mean? isn't it working?

It's the bug every time, where I get close to the water when I autoload or load the config with buttons enabled, it slows me down and then when I get near into the water, it suffocates me of drowning by decreasing the oxygen.

**Comment by notpoiu** [comment]
how is that our fault this is of a result of lsplash's bad water checks
