### ISSUE TITLE
doors script not executing

### ISSUE THREAD

**Issue by Art3mLapa** [notpoiu/mspaint#68]
the code is not executed in DOORS, and appears error
![image](https://github.com/user-attachments/assets/d923b938-6f52-498b-ad4c-5f94c3394ddc)
yesterday the script worked perfectly, also the script runs in other games counting in the DOORS lobby without errors
my executor - Xeno 1.0.8
I have already tried to clear the script files in the workspace and use another executor (solara V3)

**Comment by notpoiu** [comment]
@deividcomsono did someone change the require check again 🙃

**Comment by Art3mLapa** [comment]
after today's update in script all works
