### ISSUE TITLE
Guiding light esp is broken.

### ISSUE THREAD

**Issue by wasduiop** [notpoiu/mspaint#7]
I'm on mobile using delta x, everything works, even delete seek fe in floor 2. But, guiding light appears only after I die for some reason, my current theory is that I have to turn on chams or distance to see him ( I usually turn both off to slightly increase fps). VERY GOOD SCRIPT I luv it good work! 🚿🦆🫁🍃

**Comment by PizzaGod873** [comment]
Its for floor 2 during seek chase.

**Comment by wasduiop** [comment]
> Its for floor 2 during seek chase.

well obviously, but I found out why. When you use delete seek FE it disables guiding light, so the esp isn't broken. It's just there's nothing to see.

**Comment by notpoiu** [comment]
indeed, the guiding light thing isnt enabled if you disable seek FE. we did add a thing to prevent this tho
